language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t romulorc/travis -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true romulorc/travis npm test
after_success:
    - docker build -t romulorc/multidockertutorial-client ./client
    - docker build -t romulorc/multidockertutorial-nginx ./nginx
    - docker build -t romulorc/multidockertutorial-server ./server
    - docker build -t romulorc/multidockertutorial-worker ./worker
    
    # Login to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Retrieve those images and push to DockerHub
    - docker push romulorc/multidockertutorial-client
    - docker push romulorc/multidockertutorial-nginx
    - docker push romulorc/multidockertutorial-server
    - docker push romulorc/multidockertutorial-worker
deploy:
    edge: true,
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "multi-docker-tutorial"
    env: "MultiDockerTutorial-env"
    bucket_name: "elasticbeanstalk-ap-south-1-994437792464"
    bucket_path: "multi-docker-tutorial"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"